<?php

$labels = array();                                
$labels['filters'] = 'Pravidla';
$labels['storedfilters'] = 'Uložená pravidla';
$labels['whatfilter'] = 'Pravidlo';
$labels['searchstring'] = 'Obsahuje';
$labels['movefrom'] = 'Aplikuj na';
$labels['moveto'] = 'Uložit do';
$labels['from'] = 'Od';
$labels['to'] = 'Komu';
$labels['cc'] = 'Kopie';
$labels['subject'] = 'Předmět';
$labels['delete'] = 'Smazat';
$labels['filterpriority'] = 'Nespouštět ostatní pravidla';

$messages = array();
$messages['nosearchstring'] = "Pole 'Obsahuje' nemůže zůstat prázdné.";
$messages['successfullysaved'] = "Pravidlo bylo uloženo.";
$messages['unsuccessfullysaved'] = "Chyba: pravidlo nebylo uloženo.";
$messages['successfullydeleted'] = "Pravidlo bylo smazánoo.";
$messages['unsuccessfullydeleted'] = "Chyba: pravidlo nebylo smazáno.";
$messages['msg_if_field'] = 'Pokud pole';
$messages['msg_contains'] = 'obsahuje';
$messages['msg_move_msg_in'] = 'uložit zprávu do';
$messages['msg_move_msg_from'] = 'z';
$messages['msg_no_stored_filters'] = "Nemáte uložená pravidla.";

?>
