<?php
$labels = array();
$labels['filters'] = 'Φίλτρα';
$labels['storedfilters'] = 'Αποθηκευμένα Φίλτρα';
$labels['whatfilter'] = 'Φίλτρο';
$labels['searchstring'] = 'Περιέχει';
$labels['moveto'] = 'Μετακίνηση σε';
$labels['from'] = 'Από';
$labels['to'] = 'Σέ';
$labels['cc'] = 'Κοιν';
$labels['subject'] = 'Θέμα';
$labels['delete'] = 'Διαγραφή';
$labels['filterpriority'] = 'Να μην ισχύουν άλλοι κανόνες';
$messages = array();
$messages['nosearchstring'] = "Το πεδίο 'Περιέχει' δεν μπορεί να είναι κενό.";
$messages['successfullysaved'] = "Το φίλτρο αποθηκεύτηκε.";
$messages['unsuccessfullysaved'] = "Σφάλμα: το φίλτρο δεν αποθηκεύτηκε.";
$messages['successfullydeleted'] = "Το φίλτρο διαγράφτηκε.";
$messages['unsuccessfullydeleted'] = "Σφάλμα: το φίλτρο δεν διαγράφτηκε.";
$messages['msg_if_field'] = 'Εάν το πεδίο';
$messages['msg_contains'] = 'Περιέχει';
$messages['msg_move_msg_in'] = 'μετακίνησε το μήνυμα σε';
$messages['msg_no_stored_filters'] = "Δεν υπάρχουν αποθηκεύμενα φίλτρα.";
?>
