<?php

$labels = array();
$labels['filters'] = 'Szűrők';
$labels['storedfilters'] = 'Tárolt szűrők';
$labels['whatfilter'] = 'Szűrő';
$labels['searchstring'] = 'Tartalmaz';
$labels['moveto'] = 'Mozgassa';
$labels['from'] = 'Feladó';
$labels['to'] = 'Címzett';
$labels['cc'] = 'Másolat';
$labels['subject'] = 'Tárgy';
$labels['delete'] = 'Töröl';
$labels['filterpriority'] = 'Más szabályokra ne legyen hatással';

$messages = array();
$messages['nosearchstring'] = "A \"taralmaz\" mező nem lehet üres!";
$messages['successfullysaved'] = "A szűrő sikeresen letárolva.";
$messages['unsuccessfullysaved'] = "Hiba: a szűrő nincs tárolva.";
$messages['successfullydeleted'] = "A szűrő sikeresen törölve.";
$messages['unsuccessfullydeleted'] = "Hiba: nem sikerült a szűrő törlése.";
$messages['msg_if_field'] = 'Ha a';
$messages['msg_contains'] = 'mező tartalmaz';
$messages['msg_move_msg_in'] = 'szöveget, mozassa az üzenetet ide:';
$messages['msg_no_stored_filters'] = "Nincsenek tárolt szűrők.";

?>
