<?php
$labels = array();
$labels['filters'] = 'フィルター';
$labels['storedfilters'] = 'Stored filters';
$labels['whatfilter'] = '条件';
$labels['searchstring'] = '含まれる文字列';
$labels['moveto'] = '移動先';
$labels['from'] = 'From';
$labels['to'] = 'To';
$labels['cc'] = 'Cc';
$labels['subject'] = 'Subject';
$labels['delete'] = 'Delete';
$labels['filterpriority'] = '他のルールを適用しない';
$messages = array();
$messages['nosearchstring'] = "'含まれる文字列' を空欄にする事は出来ません。";
$messages['successfullysaved'] = "フィルタを保存しました。";
$messages['unsuccessfullysaved'] = "エラー: フィルタを保存できませんでした。";
$messages['successfullydeleted'] = "フィルタを削除しました。";
$messages['unsuccessfullydeleted'] = "エラー: フィルタを削除出来ませんでした。";
$messages['msg_if_field'] = ' ';
$messages['msg_contains'] = 'に';
$messages['msg_move_msg_in'] = 'が含まれる場合、次のフォルダーに移動します。';
$messages['msg_no_stored_filters'] = "現在、フィルターは設定されていません。";
?>
