<?php

$labels = array();
$labels['filters'] = 'Filtros';
$labels['storedfilters'] = 'Filtros salvos';
$labels['whatfilter'] = 'Filtro';
$labels['searchstring'] = 'Contém';
$labels['moveto'] = 'Mover para';
$labels['from'] = 'Remetente';
$labels['to'] = 'Destinatário';
$labels['cc'] = 'Cópia carbono';
$labels['subject'] = 'Assunto';
$labels['delete'] = 'Excluir';
$messages = array();
$messages['nosearchstring'] = "O campo 'Contém' não pode estar vazio.";
$messages['successfullysaved'] = "O fitro foi salvo com sucesso.";
$messages['unsuccessfullysaved'] = "Erro: o filtro não foi salvo.";
$messages['successfullydeleted'] = "O filtro foi excluído com sucesso.";
$messages['unsuccessfullydeleted'] = "Erro: o filtro não foi excluído.";
$messages['msg_if_field'] = 'Se o campo';
$messages['msg_contains'] = 'incluir';
$messages['msg_move_msg_in'] = 'mover a mensagem para';
$messages['msg_no_stored_filters'] = "Não existem filtros.";


?>
