<?php

$labels = array();
$labels['filters'] = 'Фильтры';
$labels['storedfilters'] = 'Правила';
$labels['whatfilter'] = 'Фильтр';
$labels['searchstring'] = 'Содержит';
$labels['movefrom'] = 'Проверять папку';
$labels['moveto'] = 'Переместить в';
$labels['from'] = 'От';
$labels['to'] = 'Кому';
$labels['cc'] = 'Копия';
$labels['subject'] = 'Тема';
$labels['delete'] = 'Удалить';
$labels['filterpriority'] = 'Не применять другие правила';

$messages = array();
$messages['nosearchstring'] = "Поле 'Содержит' не может быть пустым.";
$messages['successfullysaved'] = "Правило сохранено.";
$messages['unsuccessfullysaved'] = "Ошибка: правило не сохранено.";
$messages['successfullydeleted'] = "Правило удалено.";
$messages['unsuccessfullydeleted'] = "Ошибка: правило не удалено.";
$messages['msg_if_field'] = 'Если поле';
$messages['msg_contains'] = 'Содержит';
$messages['msg_move_msg_in'] = 'Переместить сообщение в';
$messages['msg_move_msg_from'] = 'из';
$messages['msg_no_stored_filters'] = "Правила не созданы, нет сохраненных правил.";

?>
