<?php

$labels = array();
$labels['filters'] = 'Filtreler';
$labels['storedfilters'] = 'Kayıtlı Filtreler';
$labels['whatfilter'] = 'Filtre';
$labels['searchstring'] = 'İçerir';
$labels['moveto'] = 'Hedefe Taşı';
$labels['from'] = 'From';
$labels['to'] = 'To';
$labels['cc'] = 'CC';
$labels['subject'] = 'Subject/Konu';
$labels['delete'] = 'Sil';
$labels['filterpriority'] = 'Diğer kurallara uygulama.';

$messages = array();
$messages['nosearchstring'] = " 'İçerir' alanı boş olamaz.";
$messages['successfullysaved'] = "Filtre oluşturuldu.";
$messages['unsuccessfullysaved'] = "Hata: filtre kaydedilemedi.";
$messages['successfullydeleted'] = "Filtre silindi.";
$messages['unsuccessfullydeleted'] = "Hata: Filtre silinemedi.";
$messages['msg_if_field'] = 'Eğer şu alan : ';
$messages['msg_contains'] = 'şunu içeriyorsa : ';
$messages['msg_move_msg_in'] = 'mesajı şuraya taşı';
$messages['msg_no_stored_filters'] = "Henüz bir filtre oluşturulmamış. Yeni oluşturabilirsiniz.";

?>
