<?php

$labels = array();
$labels['filters'] = 'Фільтри';
$labels['storedfilters'] = 'Правила';
$labels['whatfilter'] = 'Фільтр';
$labels['searchstring'] = 'Містить';
$labels['moveto'] = 'Перемістити';
$labels['from'] = 'Від';
$labels['to'] = 'Кому';
$labels['cc'] = 'Копія';
$labels['subject'] = 'Тема';
$labels['delete'] = 'Видалити';
$labels['filterpriority'] = 'Не застосовувати інші правила';

$messages = array();
$messages['nosearchstring'] = "Поле 'Містить' не может бути пустим.";
$messages['successfullysaved'] = "Правило збережено.";
$messages['unsuccessfullysaved'] = "Помилка: правило не збережено.";
$messages['successfullydeleted'] = "Правило видалено.";
$messages['unsuccessfullydeleted'] = "Помилка: правило не видалено.";
$messages['msg_if_field'] = 'Якщо поле';
$messages['msg_contains'] = 'Містить';
$messages['msg_move_msg_in'] = 'Перемістити повідомлення до';
$messages['msg_no_stored_filters'] = "Правила не створені, немає збережених правил.";

?>
